export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const carImageMap: { [key: string]: string } = {
  Audi: "/cars/audi.png",
  BMW: "/cars/bmw.png",
  Ford: "/cars/ford.jpg",
  Chevrolet: "/cars/chevrolet.jpg",
  Honda: "/cars/honda.jpg",
  Hyundai: "/cars/hyundai.webp",
  Kia: "/cars/kia.jpg",
  "Mercedes-Benz": "/cars/mercedes.webp",
  Nissan: "/cars/nissan.jpg",
  Toyota: "/cars/toyota.png",
  Volkswagen: "/cars/volkswagen.jpg",
  Volvo: "/cars/volvo.jpg",
  Tesla: "/cars/tesla.jpg",
  Subaru: "/cars/subaru.webp",
  "Rolls-Royce": "/cars/rolls-royce.jpg",
  Ram: "/cars/ram.jpeg",
  Porsche: "/cars/porsche.png",
  Mitsubishi: "/cars/mitsubishi.webp",
  MINI: "/cars/mini.jpeg",
  McLaren: "/cars/mclaren.jpg",
  Mazda: "/cars/mazda.jpg",
  Maserati: "/cars/maserati.jpg",
  Lincoln: "/cars/lincoln.jpeg",
  Lexus: "/cars/lexus.jpg",
  "Land Rover": "/cars/land-rover.jpg",
  Lamborghini: "/cars/lamborghini.jpg",
  Jeep: "/cars/jeep.jpg",
  Jaguar: "/cars/jaguar.jpg",
  Infiniti: "/cars/infiniti.jpg",
  GMC: "/cars/gmc.jpg",
  Fiat: "/cars/fiat.webp",
  Ferrari: "/cars/ferrari.avif",
  Dodge: "/cars/dodge.jpg",
  Citroen: "/cars/citroen.jpg",
  Chrysler: "/cars/chrysler.jpg",
  Cadillac: "/cars/cadillac.png",
  Acura: "/cars/acura.jpg",
  "Alfa Romeo": "/cars/alfa-romeo.jpg",
  "Aston Martin": "/cars/aston-martin.jpeg",
  Bentley: "/cars/bentley.png",
  Buick: "/cars/buick.avif",
};


export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];